-- Migración inicial generada automáticamente desde el esquema local.
-- Reproduce el DDL de las entidades de Elyron. No modificar a mano salvo revisión.

SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `actividades_docente` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `competency` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `groupId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `groupCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dueDate` datetime DEFAULT NULL,
  `submissions` int NOT NULL DEFAULT '0',
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Publicada',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `anuncios_comunidad` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `issuer` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `audience` text COLLATE utf8mb4_unicode_ci,
  `pinned` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `asignaciones_responsabilidad` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `userId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `responsibilityId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startsAt` datetime NOT NULL,
  `endsAt` datetime DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `assignedById` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assignmentReason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_87321f681308b5765c51a181499` (`userId`),
  KEY `FK_d765a9ed6d13ea208c2b9c88487` (`responsibilityId`),
  KEY `FK_3aca7d6462b344c4fd9505d590e` (`institutionId`),
  KEY `FK_0d06a5e4c302b7fb981cc342dd3` (`scopeId`),
  KEY `FK_8d8cbec5cb9e8bcc2efd42d0bc4` (`assignedById`),
  CONSTRAINT `FK_0d06a5e4c302b7fb981cc342dd3` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_3aca7d6462b344c4fd9505d590e` FOREIGN KEY (`institutionId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_87321f681308b5765c51a181499` FOREIGN KEY (`userId`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_8d8cbec5cb9e8bcc2efd42d0bc4` FOREIGN KEY (`assignedById`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_d765a9ed6d13ea208c2b9c88487` FOREIGN KEY (`responsibilityId`) REFERENCES `responsabilidades` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `casos` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `caseNumber` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requesterId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assignedUserId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responsibilityId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `categoryId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subcategoryId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NORMAL',
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CREADO',
  `dueAt` datetime DEFAULT NULL,
  `resolvedAt` datetime DEFAULT NULL,
  `closedAt` datetime DEFAULT NULL,
  `closedById` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reopenedAt` datetime DEFAULT NULL,
  `reopenedById` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_2e57f8f09d9975d02534d70f64` (`caseNumber`),
  KEY `FK_c8d44e5efd6c5864975b0661090` (`institutionId`),
  KEY `FK_87aff181bcb85d62275a19a8c6a` (`scopeId`),
  KEY `FK_74ebec74ab278e6af034443a462` (`requesterId`),
  KEY `FK_52c9f3a99938cf4637e586ac234` (`assignedUserId`),
  KEY `FK_7c48e4dc42b1006b926f6b7a8b5` (`responsibilityId`),
  KEY `FK_524aa803ce2acaf3c349ee4b59d` (`categoryId`),
  CONSTRAINT `FK_524aa803ce2acaf3c349ee4b59d` FOREIGN KEY (`categoryId`) REFERENCES `casos_categorias` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_52c9f3a99938cf4637e586ac234` FOREIGN KEY (`assignedUserId`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_74ebec74ab278e6af034443a462` FOREIGN KEY (`requesterId`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_7c48e4dc42b1006b926f6b7a8b5` FOREIGN KEY (`responsibilityId`) REFERENCES `responsabilidades` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_87aff181bcb85d62275a19a8c6a` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_c8d44e5efd6c5864975b0661090` FOREIGN KEY (`institutionId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `casos_categorias` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `code` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responsibilityCode` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allowedTransitions` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_1f2dd51e9de3c8a726fd4ed6fdc` (`institutionId`),
  CONSTRAINT `FK_1f2dd51e9de3c8a726fd4ed6fdc` FOREIGN KEY (`institutionId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `casos_historial` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `caseId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actorId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fromStatus` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `toStatus` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_0841b0597b2a9d534b8bc6731f6` (`caseId`),
  KEY `FK_4c6ddf925fcc83bd2746440c0e3` (`actorId`),
  CONSTRAINT `FK_0841b0597b2a9d534b8bc6731f6` FOREIGN KEY (`caseId`) REFERENCES `casos` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_4c6ddf925fcc83bd2746440c0e3` FOREIGN KEY (`actorId`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `casos_mensajes` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `caseId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `authorId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PUBLIC',
  PRIMARY KEY (`id`),
  KEY `FK_2c86a08af2b3749ac8990ffdc19` (`caseId`),
  KEY `FK_3411a02c8ca891ad057ebccb58a` (`authorId`),
  CONSTRAINT `FK_2c86a08af2b3749ac8990ffdc19` FOREIGN KEY (`caseId`) REFERENCES `casos` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_3411a02c8ca891ad057ebccb58a` FOREIGN KEY (`authorId`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `comentarios_publicacion` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `author` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `postId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_3b484e46b912ef5d62f8c42bea3` (`postId`),
  CONSTRAINT `FK_3b484e46b912ef5d62f8c42bea3` FOREIGN KEY (`postId`) REFERENCES `publicaciones_comunidad` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `competencias` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` int NOT NULL DEFAULT '0',
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_00524347546dcf0e03f8f019537` (`fichaId`),
  CONSTRAINT `FK_00524347546dcf0e03f8f019537` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `comunicados` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contenido` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `prioridad` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'media',
  `destinatario` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ficha',
  `autorId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2be2b8c334b0bac8e70e89b4d6f` (`autorId`),
  KEY `FK_e8bb61b757aceb2c3840630c2b8` (`fichaId`),
  CONSTRAINT `FK_2be2b8c334b0bac8e70e89b4d6f` FOREIGN KEY (`autorId`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_e8bb61b757aceb2c3840630c2b8` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contexto_alcances` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fichaId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `grupoId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `programaId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parentId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_48de4b500858a6c3e042c5afba8` (`institutionId`),
  KEY `FK_90569c40d0c04ee68d153749721` (`fichaId`),
  KEY `FK_cc2e02b003a55f25c0419b33a25` (`grupoId`),
  KEY `FK_dc733b1fe08c0a4a829c45c454a` (`programaId`),
  KEY `FK_bef17e9f55de5be686185d5eb46` (`parentId`),
  CONSTRAINT `FK_48de4b500858a6c3e042c5afba8` FOREIGN KEY (`institutionId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_90569c40d0c04ee68d153749721` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_bef17e9f55de5be686185d5eb46` FOREIGN KEY (`parentId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_cc2e02b003a55f25c0419b33a25` FOREIGN KEY (`grupoId`) REFERENCES `grupos` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_dc733b1fe08c0a4a829c45c454a` FOREIGN KEY (`programaId`) REFERENCES `programas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contexto_instituciones` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `code` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_ed920b2a37bab06edfe090545d` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `docentes_grupos` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `grupoId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `docenteId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `asignatura` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activo` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `FK_1d2b237777cf11586ca9cdda84a` (`grupoId`),
  KEY `FK_0eb62b481f388e78f0b387670e4` (`docenteId`),
  CONSTRAINT `FK_0eb62b481f388e78f0b387670e4` FOREIGN KEY (`docenteId`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_1d2b237777cf11586ca9cdda84a` FOREIGN KEY (`grupoId`) REFERENCES `grupos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `documentos_personales` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'academico',
  `descripcion` text COLLATE utf8mb4_unicode_ci,
  `url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaEmision` datetime DEFAULT NULL,
  `aprendizId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `caseId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_195c66037baa040dfc015b630a1` (`aprendizId`),
  KEY `FK_9f5b84a63a33fa76d53968792c3` (`caseId`),
  CONSTRAINT `FK_195c66037baa040dfc015b630a1` FOREIGN KEY (`aprendizId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_9f5b84a63a33fa76d53968792c3` FOREIGN KEY (`caseId`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `elir_conversaciones` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `ownerId` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Nueva conversación',
  `program` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mode` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'responder',
  PRIMARY KEY (`id`),
  KEY `IDX_cceea5a95cb33aae1d2a7864f3` (`ownerId`),
  KEY `IDX_767d2327bd3d928b8fe0458d5d` (`ownerId`,`updatedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `elir_documentos` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `ownerId` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `originalName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `storageName` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `storagePath` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mime` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ext` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sizeBytes` bigint NOT NULL,
  `sha256` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `extractedText` longtext COLLATE utf8mb4_unicode_ci,
  `kind` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'file',
  `program` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ready',
  `expiresAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_14d527aa1ba397a667e6f4ad82` (`ownerId`),
  KEY `IDX_e69c12001ba46f80d60cf5edd8` (`ownerId`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `elir_mensajes` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `conversationId` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `sources` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_a944fd0bbefee2ac8617794c1a` (`conversationId`,`createdAt`),
  CONSTRAINT `FK_2f6c84536aaf0cd54d6b1e9c035` FOREIGN KEY (`conversationId`) REFERENCES `elir_conversaciones` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `elir_planes` (
  `id` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `priceCOP` int NOT NULL,
  `tagline` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `features` json NOT NULL,
  `limits` json NOT NULL,
  `sortOrder` int NOT NULL DEFAULT '0',
  `active` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `IDX_9eddd32c91dd831fb0d770794c` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `elir_uso` (
  `userId` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `planId` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'free',
  `messages` int NOT NULL DEFAULT '0',
  `files` int NOT NULL DEFAULT '0',
  `images` int NOT NULL DEFAULT '0',
  `advancedTasks` int NOT NULL DEFAULT '0',
  `inputTokens` bigint DEFAULT NULL,
  `outputTokens` bigint DEFAULT NULL,
  `documentProcessing` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`userId`,`date`),
  KEY `IDX_6b70f77604f317bff22f42cf04` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `empresas` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nit` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isActive` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `empresas_capacitadores` (
  `companyId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trainerId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`companyId`,`trainerId`),
  KEY `IDX_0df8f3128153f537364706d6c8` (`companyId`),
  KEY `IDX_74cbee6f6f38c091f42ac2a1e3` (`trainerId`),
  CONSTRAINT `FK_0df8f3128153f537364706d6c8a` FOREIGN KEY (`companyId`) REFERENCES `empresas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_74cbee6f6f38c091f42ac2a1e35` FOREIGN KEY (`trainerId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `entregas_docente` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `student` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activityTitle` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activityType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `groupCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `submittedAt` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT '1',
  `late` tinyint NOT NULL DEFAULT '0',
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Pendiente',
  `grade` int DEFAULT NULL,
  `feedback` text COLLATE utf8mb4_unicode_ci,
  `actividadId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_3e4e79c6469c07614e1a6b84c07` (`actividadId`),
  CONSTRAINT `FK_3e4e79c6469c07614e1a6b84c07` FOREIGN KEY (`actividadId`) REFERENCES `actividades_docente` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `eventos_calendario` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startDate` datetime NOT NULL,
  `endDate` datetime NOT NULL,
  `allDay` tinyint NOT NULL DEFAULT '0',
  `color` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default',
  `createdById` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attendees` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `FK_8bb9f8c15beac1f338d7c5c2f8f` (`createdById`),
  CONSTRAINT `FK_8bb9f8c15beac1f338d7c5c2f8f` FOREIGN KEY (`createdById`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `evidencias` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `files` text COLLATE utf8mb4_unicode_ci,
  `resultadoId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `submittedById` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewedAt` datetime DEFAULT NULL,
  `feedback` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institutionContextId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `programaId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fichaId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `grupoId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responsibleUserId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewedById` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_08bba91bb4bcf468f1d0b8db6b0` (`resultadoId`),
  KEY `FK_dfa88e88364bbdb9a01a7804cd4` (`submittedById`),
  KEY `FK_f354e2fc17c3e8343d5ce774a26` (`institutionContextId`),
  KEY `FK_c687838c1bb080dc4ff2a3146e3` (`scopeId`),
  KEY `FK_8f93ea7915084919780fce3dfc9` (`programaId`),
  KEY `FK_06b3a6943d16196bd3a48b9963b` (`fichaId`),
  KEY `FK_f6f4243563d59c0746465d9442b` (`grupoId`),
  CONSTRAINT `FK_06b3a6943d16196bd3a48b9963b` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_08bba91bb4bcf468f1d0b8db6b0` FOREIGN KEY (`resultadoId`) REFERENCES `resultados` (`id`),
  CONSTRAINT `FK_8f93ea7915084919780fce3dfc9` FOREIGN KEY (`programaId`) REFERENCES `programas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_c687838c1bb080dc4ff2a3146e3` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_dfa88e88364bbdb9a01a7804cd4` FOREIGN KEY (`submittedById`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_f354e2fc17c3e8343d5ce774a26` FOREIGN KEY (`institutionContextId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_f6f4243563d59c0746465d9442b` FOREIGN KEY (`grupoId`) REFERENCES `grupos` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ficha_anuncios` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contenido` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `prioridad` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'media',
  `categoria` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'anuncio',
  `autorId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2632287e33c3014af143f58aed4` (`autorId`),
  KEY `FK_b0988481ae258c1f8f15060dc2b` (`fichaId`),
  CONSTRAINT `FK_2632287e33c3014af143f58aed4` FOREIGN KEY (`autorId`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_b0988481ae258c1f8f15060dc2b` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ficha_inquietudes` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `estado` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'abierta',
  `categoria` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'general',
  `autorId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_e3974a10b2bc4a6fbedd4b8dd8e` (`autorId`),
  KEY `FK_4a8c59946f95bf2f3a18718dc71` (`fichaId`),
  CONSTRAINT `FK_4a8c59946f95bf2f3a18718dc71` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_e3974a10b2bc4a6fbedd4b8dd8e` FOREIGN KEY (`autorId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ficha_instructores` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `instructorId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activo` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `FK_d317ae95774e1c431db7e8f2ca4` (`fichaId`),
  KEY `FK_7fcd41775a0a3b1859e9d0a4e2a` (`instructorId`),
  CONSTRAINT `FK_7fcd41775a0a3b1859e9d0a4e2a` FOREIGN KEY (`instructorId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_d317ae95774e1c431db7e8f2ca4` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fichas` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startDate` datetime NOT NULL,
  `endDate` datetime NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `companyId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipoPrograma` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `programaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institutionContextId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_a8ca6464183d9b119d57733d74f` (`companyId`),
  KEY `FK_79a6cdef81dd2580a8c16ab7e5a` (`programaId`),
  KEY `FK_bee604e4328a930fa9de4138164` (`institutionContextId`),
  KEY `FK_306e45bdf2525fdfb7ec8c87641` (`scopeId`),
  CONSTRAINT `FK_306e45bdf2525fdfb7ec8c87641` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_79a6cdef81dd2580a8c16ab7e5a` FOREIGN KEY (`programaId`) REFERENCES `programas` (`id`),
  CONSTRAINT `FK_a8ca6464183d9b119d57733d74f` FOREIGN KEY (`companyId`) REFERENCES `empresas` (`id`),
  CONSTRAINT `FK_bee604e4328a930fa9de4138164` FOREIGN KEY (`institutionContextId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `grupos` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `grado` int NOT NULL,
  `nivel` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'basica_secundaria',
  `jornada` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manana',
  `anioLectivo` int NOT NULL DEFAULT '2026',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `colegio` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institutionContextId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_002b0be745e50c02cab604c40a` (`code`),
  KEY `FK_21c4820d97d22898e64d08df61f` (`institutionContextId`),
  KEY `FK_9e0c4041dacf3f285978bcea421` (`scopeId`),
  CONSTRAINT `FK_21c4820d97d22898e64d08df61f` FOREIGN KEY (`institutionContextId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_9e0c4041dacf3f285978bcea421` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `instituciones_catalogo` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `nombre` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `detalles` json DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `likes_publicaciones` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `postId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_2e58f66afcaf8446fab707ba37` (`postId`,`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `llamadas` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `startDate` datetime NOT NULL,
  `endDate` datetime NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `requirements` text COLLATE utf8mb4_unicode_ci,
  `maxParticipants` int DEFAULT NULL,
  `createdById` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `applicationsCount` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_9d5f9fe4c391a4fab979fc29778` (`createdById`),
  CONSTRAINT `FK_9d5f9fe4c391a4fab979fc29778` FOREIGN KEY (`createdById`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `log_auditoria` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `actor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `time` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `institutionId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responsibilityId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `permission` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `beforeValue` text COLLATE utf8mb4_unicode_ci,
  `afterValue` text COLLATE utf8mb4_unicode_ci,
  `ip` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `mensajes_chat` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `senderId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `receiverId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `isRead` tinyint NOT NULL DEFAULT '0',
  `roomId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fichaId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institucion` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sena',
  `grupoId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_00e257a3dab6ad7d302e4c498c5` (`senderId`),
  KEY `FK_6757ed9bdf3f38ac70b888b65fe` (`receiverId`),
  CONSTRAINT `FK_00e257a3dab6ad7d302e4c498c5` FOREIGN KEY (`senderId`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_6757ed9bdf3f38ac70b888b65fe` FOREIGN KEY (`receiverId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notificaciones` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'info',
  `isRead` tinyint NOT NULL DEFAULT '0',
  `userId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_fa9356bbbd322d6fafcc5921219` (`userId`),
  CONSTRAINT `FK_fa9356bbbd322d6fafcc5921219` FOREIGN KEY (`userId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ofertas_trabajo` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `salary` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `expiresAt` datetime DEFAULT NULL,
  `requirements` text COLLATE utf8mb4_unicode_ci,
  `postedById` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `applicationsCount` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_127aba2bc4a83ba37fc3ea02bbe` (`postedById`),
  CONSTRAINT `FK_127aba2bc4a83ba37fc3ea02bbe` FOREIGN KEY (`postedById`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_reset_tokens` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `userId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenHash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiresAt` datetime NOT NULL,
  `usedAt` datetime DEFAULT NULL,
  `revokedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_1143abb8c3fad8b06dd857a8c9` (`tokenHash`),
  KEY `IDX_f75f11ca4ed69b941336c5d0e3` (`expiresAt`),
  KEY `IDX_d6a19d4b4f6c62dcd29daa497e` (`userId`),
  CONSTRAINT `FK_d6a19d4b4f6c62dcd29daa497e2` FOREIGN KEY (`userId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `perfiles_colegio` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `colegio` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `grado` int NOT NULL,
  `jornada` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipoDocumento` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `usuarioId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `documentoHash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombres` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apellidos` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ciudad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anioAcademico` int DEFAULT NULL,
  `estadoAcademico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaEstimadaFinalizacion` date DEFAULT NULL,
  `estadoElyron` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianza` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianzas` text COLLATE utf8mb4_unicode_ci,
  `estimacion` text COLLATE utf8mb4_unicode_ci,
  `numeroDocumento` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_460a4cfcb6003f1b25403047b1` (`usuarioId`),
  UNIQUE KEY `REL_460a4cfcb6003f1b25403047b1` (`usuarioId`),
  UNIQUE KEY `IDX_1132c5d3929587ee6a9323622b` (`documentoHash`),
  CONSTRAINT `FK_460a4cfcb6003f1b25403047b1e` FOREIGN KEY (`usuarioId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `perfiles_sena` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `numeroFicha` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `programaFormacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nivelFormacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `centroFormacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `regional` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `etapa` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'lectiva',
  `modalidadProductiva` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaInicio` date DEFAULT NULL,
  `usuarioId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipoDocumento` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numeroDocumento` text COLLATE utf8mb4_unicode_ci,
  `documentoHash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombres` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apellidos` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipoFormacion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigoPrograma` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ciudad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modalidad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jornada` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaMatricula` date DEFAULT NULL,
  `estadoAcademico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duracionMeses` int DEFAULT NULL,
  `fechaEstimadaFinalizacion` date DEFAULT NULL,
  `estadoElyron` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianza` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianzas` text COLLATE utf8mb4_unicode_ci,
  `estimacion` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_93e937488dcbeb75e00990a78e` (`usuarioId`),
  UNIQUE KEY `REL_93e937488dcbeb75e00990a78e` (`usuarioId`),
  UNIQUE KEY `IDX_e1543a4fb79aeb190d63c55d82` (`documentoHash`),
  CONSTRAINT `FK_93e937488dcbeb75e00990a78e0` FOREIGN KEY (`usuarioId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `perfiles_universidad` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `codigoEstudiantil` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `universidad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `facultad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `programaAcademico` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `semestre` int NOT NULL,
  `jornada` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creditosAprobados` int DEFAULT NULL,
  `usuarioId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipoDocumento` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numeroDocumento` text COLLATE utf8mb4_unicode_ci,
  `documentoHash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombres` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apellidos` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nivelAcademico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anioIngreso` int DEFAULT NULL,
  `periodoIngreso` int DEFAULT NULL,
  `modalidad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creditosPrograma` int DEFAULT NULL,
  `totalSemestres` int DEFAULT NULL,
  `estadoAcademico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `semestresRestantes` int DEFAULT NULL,
  `fechaEstimadaFinalizacion` date DEFAULT NULL,
  `estadoElyron` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianza` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confianzas` text COLLATE utf8mb4_unicode_ci,
  `estimacion` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_44b47ff09bdb8abf331b04c6ee` (`codigoEstudiantil`),
  UNIQUE KEY `IDX_c0e1cbddfd12323f196dbc775b` (`usuarioId`),
  UNIQUE KEY `REL_c0e1cbddfd12323f196dbc775b` (`usuarioId`),
  UNIQUE KEY `IDX_0fb9be6a1f3327a8f4263f95c7` (`documentoHash`),
  CONSTRAINT `FK_c0e1cbddfd12323f196dbc775be` FOREIGN KEY (`usuarioId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `permisos` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `module` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_e9ab74f7d63bcb3084974b4f27` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `programas` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `institutionId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `groupLabel` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instructorCount` int NOT NULL DEFAULT '0',
  `apprenticeCount` int NOT NULL DEFAULT '0',
  `duracionMeses` int DEFAULT NULL,
  `institutionContextId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopeId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_b9b34279ffcade705aa40fdf5d7` (`institutionContextId`),
  KEY `FK_67b16004282f73655d0fda8e6e8` (`scopeId`),
  CONSTRAINT `FK_67b16004282f73655d0fda8e6e8` FOREIGN KEY (`scopeId`) REFERENCES `contexto_alcances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_b9b34279ffcade705aa40fdf5d7` FOREIGN KEY (`institutionContextId`) REFERENCES `contexto_instituciones` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `publicaciones_comunidad` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `images` text COLLATE utf8mb4_unicode_ci,
  `likesCount` int NOT NULL DEFAULT '0',
  `commentsCount` int NOT NULL DEFAULT '0',
  `authorId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parentId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isVisible` tinyint NOT NULL DEFAULT '1',
  `authorRole` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `groupCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_d811416d8a08dca4e3df36eab70` (`authorId`),
  CONSTRAINT `FK_d811416d8a08dca4e3df36eab70` FOREIGN KEY (`authorId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `recursos_biblioteca` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'libro',
  `autor` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descripcion` text COLLATE utf8mb4_unicode_ci,
  `estado` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'disponible',
  `prestadoAId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaDevolucion` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_c7f45d88d3070a586aefb3c0d7f` (`prestadoAId`),
  CONSTRAINT `FK_c7f45d88d3070a586aefb3c0d7f` FOREIGN KEY (`prestadoAId`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `remisiones` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `aprendizId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `responsableId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sostenimiento',
  `estado` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'postulado',
  `chatActivo` tinyint NOT NULL DEFAULT '0',
  `motivo` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `FK_f72716b9d1c58e422c17d57e9dc` (`aprendizId`),
  KEY `FK_88fe8a45bba18bdff3224f907f5` (`responsableId`),
  KEY `FK_07df139f562c4a228dba771c699` (`fichaId`),
  CONSTRAINT `FK_07df139f562c4a228dba771c699` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_88fe8a45bba18bdff3224f907f5` FOREIGN KEY (`responsableId`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_f72716b9d1c58e422c17d57e9dc` FOREIGN KEY (`aprendizId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `remisiones_colegio` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `estudianteId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `responsableId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `grupoId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'orientacion',
  `estado` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'postulado',
  `chatActivo` tinyint NOT NULL DEFAULT '0',
  `motivo` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `FK_0702c80e5a42678887270a8e5b0` (`estudianteId`),
  KEY `FK_8cf2050c805ec4a199350024589` (`responsableId`),
  KEY `FK_10d60dc302aa6f667ba84ad1649` (`grupoId`),
  CONSTRAINT `FK_0702c80e5a42678887270a8e5b0` FOREIGN KEY (`estudianteId`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `FK_10d60dc302aa6f667ba84ad1649` FOREIGN KEY (`grupoId`) REFERENCES `grupos` (`id`),
  CONSTRAINT `FK_8cf2050c805ec4a199350024589` FOREIGN KEY (`responsableId`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reportes_moderacion` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `contentExcerpt` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reportedBy` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reportedByRole` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pendiente',
  `authorName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reportes_publicacion` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reportedBy` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reportedByRole` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pendiente',
  `postId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `authorName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contentExcerpt` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_0150d8a75ace13e516d502b0cf4` (`postId`),
  CONSTRAINT `FK_0150d8a75ace13e516d502b0cf4` FOREIGN KEY (`postId`) REFERENCES `publicaciones_comunidad` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `responsabilidades` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `domain` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_a101c13257e6c1f310f02c821b` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resultados` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `competenciaId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_db1aa069165211c59744ac2efe5` (`competenciaId`),
  CONSTRAINT `FK_db1aa069165211c59744ac2efe5` FOREIGN KEY (`competenciaId`) REFERENCES `competencias` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `roles` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_648e3f5447f725579d7d4ffdfb` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `roles_permisos` (
  `roleId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `permissionId` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`roleId`,`permissionId`),
  KEY `IDX_44b06df624f1a4569e6b44a8d9` (`roleId`),
  KEY `IDX_4950e6400c8b70201ed81e3a59` (`permissionId`),
  CONSTRAINT `FK_44b06df624f1a4569e6b44a8d99` FOREIGN KEY (`roleId`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_4950e6400c8b70201ed81e3a597` FOREIGN KEY (`permissionId`) REFERENCES `permisos` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `solicitudes` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `titulo` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` text COLLATE utf8mb4_unicode_ci,
  `tipo` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'general',
  `estado` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'abierta',
  `aprendizId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_7c202f302c7755dc4c53b819056` (`aprendizId`),
  CONSTRAINT `FK_7c202f302c7755dc4c53b819056` FOREIGN KEY (`aprendizId`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `usuarios` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isActive` tinyint NOT NULL DEFAULT '1',
  `isEmailVerified` tinyint NOT NULL DEFAULT '0',
  `roleId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refreshToken` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institucion` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sena',
  `fichaId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `esVocero` tinyint NOT NULL DEFAULT '0',
  `esVoceroSuplente` tinyint NOT NULL DEFAULT '0',
  `grupoId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `esPersonero` tinyint NOT NULL DEFAULT '0',
  `esPersoneroSuplente` tinyint NOT NULL DEFAULT '0',
  `emailVerificationToken` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emailVerificationExpiresAt` datetime DEFAULT NULL,
  `authProvider` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authProviderId` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tokenVersion` int NOT NULL DEFAULT '0',
  `tipoDocumento` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numeroDocumento` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direccion` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `titulosAcademicos` json DEFAULT NULL,
  `educacionComplementaria` json DEFAULT NULL,
  `experienciaLaboral` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_446adfc18b35418aac32ae0b7b` (`email`),
  KEY `FK_103ef6f6e21ebd7a1559716248c` (`roleId`),
  KEY `FK_83366efe683103d1cfba29dc440` (`companyId`),
  KEY `FK_d51fec5cba02787e3089c50af94` (`fichaId`),
  KEY `FK_94000cf758b5eb25152cc4eac70` (`grupoId`),
  CONSTRAINT `FK_103ef6f6e21ebd7a1559716248c` FOREIGN KEY (`roleId`) REFERENCES `roles` (`id`),
  CONSTRAINT `FK_83366efe683103d1cfba29dc440` FOREIGN KEY (`companyId`) REFERENCES `empresas` (`id`),
  CONSTRAINT `FK_94000cf758b5eb25152cc4eac70` FOREIGN KEY (`grupoId`) REFERENCES `grupos` (`id`),
  CONSTRAINT `FK_d51fec5cba02787e3089c50af94` FOREIGN KEY (`fichaId`) REFERENCES `fichas` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
